theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: blog.mallaichte.live
author: Jinx
email: contact@mallaichte.live
description: > # this means to ignore newlines until "baseurl:"
  Ongoing and completed projects.
# social links
twitter_username: ctfJinx # DO NOT include the @ character, or else the build will fail!
github_username:  Mallaichte # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
